on: workflow_dispatch

jobs:
  apk:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    container:
      image: ghcr.io/tempemployee/tailscale-android-builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: make apk
        env:
          TAILSCALE_SERVER: ${{ secrets.TAILSCALE_SERVER }}
        run: |
          make patch
          make apk
      - name: save apk artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: tailscale-android/tailscale-debug.apk
