name: 构建docker

on: workflow_dispatch

jobs:
  make_docker:
    runs-on: ubuntu-latest
    steps:
      - name: 获取项目小写用户名
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: 克隆项目
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 查看当前路径
        run: |
          pwd
          echo 'OWNER: '"$OWNER"
          echo 'OWNER_LC: '"$OWNER_LC"
      - name: 查看当前目录下的文件
        run: |
          echo 'OWNER: '"$OWNER"
          echo 'OWNER_LC: '"$OWNER_LC"
          ls -alh
      - name: 通过Docker登录GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: 创建镜像
        run: |
          make docker
      - name: 为镜像打标签
        run: |
          docker tag ${{ github.repository }} ghcr.io/${{ github.repository }}
  make_apk:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: make apk
        env:
          TAILSCALE_SERVER: ${{ secrets.TAILSCALE_SERVER }}
        run: |
          make patch
          make apk
      - name: save apk artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: tailscale-android/tailscale-debug.apk
