name: 构建docker

on: workflow_dispatch

jobs:
  make_docker:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆项目
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 查看当前路径
        run: pwd
      - name: 查看当前目录下的文件
        run: ls -alh
      - name: 创建镜像
        run: make docker
      - name: 为镜像打标签
        run: docker tag tailscale-android-builder ghcr.io/${{ github.actor }}/tailscale-android-builder
      - name: 推送镜像
        run: docker push ghcr.io/${{ github.actor }}/tailscale-android-builder
