name: 构建docker

on: workflow_dispatch

jobs:
  make_docker:
    runs-on: ubuntu-latest
    # 这里用于定义 GITHUB_TOKEN 的权限
    permissions:
      packages: write
      contents: read
    steps:
      - name: 获取项目小写用户名
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: 克隆项目
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 查看当前路径
        run: |
          pwd
          echo 'OWNER: '"$OWNER"
          echo 'OWNER_LC: '"$OWNER_LC"
      - name: 查看当前目录下的文件
        run: |
          echo 'OWNER: '"$OWNER"
          echo 'OWNER_LC: '"$OWNER_LC"
          ls -alh
      - name: 通过Docker登录GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: 创建镜像
        run: |
          make docker
      - name: 为镜像打标签
        run: |
          docker tag ${{ github.repository }} ghcr.io/"$OWNER_LC"/${{ github.repository }}
      - name: 发布镜像
        run: |
          docker push ghcr.io/"$OWNER_LC"/${{ github.repository }}
